### ISSUE TITLE
Override email content via realm attributes 

### ISSUE THREAD

**Issue by shehabghazy** [p2-inc/keycloak-themes#39]
I'm trying to override the verification-email content via realm attributes using but it doesn't reflect properly in the email..

I have tried this key `_providerConfig.theme.email.messages.verification-email` and after reviewing the code I tried `_providerConfig.messages.email.verification-email` but both of them are not working

I'm using phase-two container `v24.0.5` deployed on K8s with this entry point:

```
start-dev --import-realm --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-cache-themes=false
```

how should I apply that or have I missed any thing ?

**Comment by shehabghazy** [comment]
I have these attributes:

- key: `_providerConfig.theme.email.templates.email-verification.ftl`
- value: complete ftl template

- key: `_providerConfig.theme.email.templates.email-verification`
- value: complete ftl template


but I still receive the default template for verification email

Also I want to ask if I can modify the logo and this message:

"Someone has created a {2} account with this email address. If this was you, click the link below to verify your email address\n\n{0}\n\nThis link will expire within {3}.\n\nIf you didn''t create this account, just ignore this message."

can I modify them without changing the whole template ?

**Comment by shehabghazy** [comment]
thanks @xgp for your help but I have these attributes and I still receive the default template for verification email:

- key: `_providerConfig.theme.email.templates.email-verification.ftl`
- value: complete ftl template

- key: `_providerConfig.theme.email.templates.email-verification`
- value: complete ftl template


Also I want to ask if I can modify the logo and this message:

"Someone has created a {2} account with this email address. If this was you, click the link below to verify your email address\n\n{0}\n\nThis link will expire within {3}.\n\nIf you didn''t create this account, just ignore this message."

can I modify them without changing the whole template ?

**Comment by xgp** [comment]
Have you set the theme to “Attributes” in the realm settings?

**Comment by shehabghazy** [comment]
yes .. also when I modify the template from emails tab directly -not from attributes- the changes reflected in the received email


![Screenshot from 2024-10-02 13-06-27](https://github.com/user-attachments/assets/8fe69655-b92e-47df-aad1-201c4e99ffc4)

**Comment by shehabghazy** [comment]
@xgp  yes .. also when I modify the template from emails tab directly -not from attributes- the changes reflected in the received email

![Screenshot from 2024-10-02 13-08-19](https://github.com/user-attachments/assets/0d8c2f8a-3ce1-40cf-ba69-b2a29d313955)


![Screenshot from 2024-10-02 13-06-27](https://github.com/user-attachments/assets/8fe69655-b92e-47df-aad1-201c4e99ffc4)

**Comment by xgp** [comment]
Can you set DEBUG logging and paste the output here?

**Comment by shehabghazy** [comment]
@xgp 

It worked when I used this key for the attribute:
`_providerConfig.theme.email.templates.html/email-verification.mustache`

![image](https://github.com/user-attachments/assets/1ce955a9-fb03-479d-91f9-480daaba8941)


But this force me to provide full ftl template .. can I pass some attributes to modify only the text and image ?
