### ISSUE TITLE
Logo URL fetching returns an error if the url contains a whitespace

### ISSUE THREAD

**Issue by jonathanhallee** [p2-inc/keycloak-themes#44]
Repro steps:

In Styles -> General -> Logo URL, enter a valid url, but put a whitespace at the beginning.

The UI accepts it, however during the login the call to get the images returns a 404 mentioning to check the server logs in debug to know the root cause (which I don't believe we have access to with the free tier)

Took me a while to find this but a simple trim should fix it

**Comment by pnzrr** [comment]
Thanks for the report. We'll take care of that 🙌

**Comment by pnzrr** [comment]
@jonathanhallee we've also included a validation fix in the UI 
https://github.com/p2-inc/keycloak/tree/26.0.0_orgs_admin_ui

this release will go out when we release 26 soon
